[package]
name = "arranger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
dirs = "5.0"
clap = { version = "4.3.16", features = ["derive"] }
